#!/usr/bin/env python3
r"""Generate LaTeX publication lists from data/publications.yaml.

  python3 tools/build_cv.py [--out DIR]

Writes DIR/pubs_<section>.tex (one \pubitem per entry) plus pubs_selected.tex
for the entries flagged `selected: true`. Nothing here is hand-edited; edit
data/publications.yaml and re-run.
"""
import argparse, html, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = Path.home() / "OneDrive/Documents/Resume/Current/generated"

SECTIONS = ["journal", "book", "proceedings",
            "invited", "talk", "thesis", "report"]

SPECIALS = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
            "_": r"\_", "{": r"\{", "}": r"\}",
            "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}


def detag(s):
    """HTML fragment -> plain text."""
    s = re.sub(r"<[^>]+>", "", s or "")
    s = html.unescape(s)
    return re.sub(r"\s+", " ", s).strip()


def tex(s):
    s = s.replace("\\", r"\textbackslash{}")
    for a, b in SPECIALS.items():
        s = s.replace(a, b)
    # unicode the base fonts do not carry
    for a, b in {"–": "--", "—": "---", "’": "'", "‘": "`",
                 "“": "``", "”": "''", "é": r"\'e", "è": r"\`e",
                 "ü": r'\"u', "ö": r'\"o', "ä": r'\"a', "ç": r"\c{c}",
                 "±": r"$\pm$", "×": r"$\times$", "°": r"$^\circ$",
                 "è": r"\`e", "í": r"\'i", "á": r"\'a", "ñ": r"\~n",
                 "‑": "-", " ": "~"}.items():
        s = s.replace(a, b)
    return s


SELF = re.compile(r"\bGhosh\.?,\s*D\.?")


def authors_tex(a):
    """Bold the subject's own name so a reader finds it in a long list."""
    a = tex(detag(a))
    return SELF.sub(lambda m: r"\textbf{" + m.group(0) + "}", a)


def item(rec, with_doi=True):
    parts = []
    if rec.get("authors"):
        parts.append(authors_tex(rec["authors"]) + ", ")
    parts.append(r"\emph{" + tex(detag(rec["title"])) + "}")
    cite = detag(rec.get("citation", ""))
    if cite:
        parts.append(", " + tex(cite))
    if with_doi and rec.get("doi"):
        d = rec["doi"]
        parts.append(r", \doi{" + tex(d) + "}")
    parts.append(".")
    if rec.get("also"):
        parts.append(" " + tex("Also presented at: " + detag(rec["also"]) + "."))
    return r"\pubitem{" + "".join(parts) + "}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    args = ap.parse_args()
    out = Path(args.out).expanduser()
    out.mkdir(parents=True, exist_ok=True)

    import yaml
    recs = yaml.safe_load((ROOT / "data" / "publications.yaml").read_text(encoding="utf-8"))
    for r in recs:
        r.setdefault("year", 0)
    recs.sort(key=lambda r: (r.get("year") or 0, r.get("month") or 0), reverse=True)

    banner = "% GENERATED by tools/build_cv.py from data/publications.yaml -- do not edit.\n"

    total = 0
    for sec in SECTIONS:
        rs = [r for r in recs if r["section"] == sec]
        body = banner + "\n".join(item(r) for r in rs) + "\n"
        (out / f"pubs_{sec}.tex").write_text(body, encoding="utf-8")
        if rs:
            print(f"  pubs_{sec}.tex      {len(rs):3d}")
        total += len(rs)

    sel = [r for r in recs if r.get("selected")]
    (out / "pubs_selected.tex").write_text(
        banner + "\n".join(item(r) for r in sel) + "\n", encoding="utf-8")
    print(f"  pubs_selected.tex  {len(sel):3d}")

    counts = {s: sum(1 for r in recs if r["section"] == s) for s in SECTIONS}
    stats = banner + "".join(
        f"\\newcommand{{\\n{s}}}{{{counts[s]}}}\n" for s in SECTIONS)
    stats += f"\\newcommand{{\\ntotal}}{{{total}}}\n"
    (out / "pubs_counts.tex").write_text(stats, encoding="utf-8")
    print(f"\n{total} entries -> {out}")


if __name__ == "__main__":
    main()
