"""Shared page shell: <head> with SEO metadata, masthead, nav, footer.

Every .html at the repo root is generated. Edit content/<page>.html for body
copy, data/site.yaml for metadata, then run tools/build_site.py.
"""
import html, json

GEN_WARNING = "<!-- GENERATED by tools/build_site.py from content/{src} + data/site.yaml. Do not edit this file; edit the source and rebuild. -->"


def esc(s):
    return html.escape(str(s), quote=True)


def head(site, page_file, page, prefix=""):
    p = site["profile"]
    base = p["base_url"].rstrip("/")
    canon = f"{base}/" if page_file == "index.html" else f"{base}/{page_file}"
    desc = page["description"]
    title = page["title"]
    bits = [
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f"<title>{esc(title)}</title>",
        f'<meta name="description" content="{esc(desc)}">',
        f'<meta name="author" content="{esc(p["name"])}">',
        f'<link rel="canonical" href="{esc(canon)}">',
        ('<meta name="robots" content="noindex, follow">' if page_file == "404.html"
         else '<meta name="robots" content="index, follow, max-image-preview:large">'),
        # Open Graph
        '<meta property="og:type" content="website">',
        f'<meta property="og:site_name" content="{esc(p["name"])}">',
        f'<meta property="og:title" content="{esc(title)}">',
        f'<meta property="og:description" content="{esc(desc)}">',
        f'<meta property="og:url" content="{esc(canon)}">',
        f'<meta property="og:image" content="{esc(base)}/{esc(p["photo"])}">',
        # Twitter
        '<meta name="twitter:card" content="summary">',
        f'<meta name="twitter:title" content="{esc(title)}">',
        f'<meta name="twitter:description" content="{esc(desc)}">',
        f'<meta name="twitter:image" content="{esc(base)}/{esc(p["photo"])}">',
        # icon: inline SVG monogram, no extra request
        '<link rel="icon" href="data:image/svg+xml,'
        "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E"
        "%3Crect width='64' height='64' rx='12' fill='%231f4bd8'/%3E"
        "%3Ctext x='32' y='45' font-family='Helvetica,Arial,sans-serif' font-size='38'"
        " font-weight='bold' fill='white' text-anchor='middle'%3EDG%3C/text%3E%3C/svg%3E\">",
        f'<link rel="stylesheet" href="{prefix}assets/style.css">',
    ]
    return "\n".join(bits)


def person_jsonld(site):
    p = site["profile"]
    base = p["base_url"].rstrip("/")
    data = {
        "@context": "https://schema.org",
        "@type": "Person",
        "@id": f"{base}/#person",
        "name": p["name"],
        "givenName": "Debojyoti",
        "familyName": "Ghosh",
        "jobTitle": p["role"],
        "url": base + "/",
        "image": f"{base}/{p['photo']}",
        "identifier": {
            "@type": "PropertyValue",
            "propertyID": "ORCID",
            "value": f"https://orcid.org/{p['orcid']}",
        },
        "affiliation": {
            "@type": "Organization",
            "name": p["employer"],
            "url": p["employer_url"],
            "department": {"@type": "Organization", "name": p["org"], "url": p["org_url"]},
        },
        "alumniOf": [
            {"@type": "CollegeOrUniversity", "name": "University of Maryland, College Park"},
            {"@type": "CollegeOrUniversity", "name": "Indian Institute of Technology Bombay"},
        ],
        "knowsAbout": p["knows_about"],
        "sameAs": [
            f"https://orcid.org/{p['orcid']}",
            p["scholar"], p["github"], p["gitlab"], p["linkedin"], p["researchgate"],
        ],
    }
    return ('<script type="application/ld+json">\n'
            + json.dumps(data, indent=2, ensure_ascii=False) + "\n</script>")


def breadcrumb_jsonld(site, page_file, page):
    """Breadcrumb trail helps Google render a sensible result path."""
    if page_file == "index.html":
        return ""
    base = site["profile"]["base_url"].rstrip("/")
    data = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": base + "/"},
            {"@type": "ListItem", "position": 2, "name": page["heading"],
             "item": f"{base}/{page_file}"},
        ],
    }
    return ('<script type="application/ld+json">\n'
            + json.dumps(data, indent=2, ensure_ascii=False) + "\n</script>")


def nav(site, page_file, prefix=""):
    out = ['<nav class="nav" aria-label="Main">', "<ul>"]
    for item in site["nav"]:
        cur = ' aria-current="page"' if item["file"] == page_file else ""
        out.append(f'<li><a href="{prefix}{esc(item["file"])}"{cur}>{esc(item["label"])}</a></li>')
    out += ["</ul>", "</nav>"]
    return "\n".join(out)


def masthead(site, page_file, prefix=""):
    p = site["profile"]
    return f"""<header class="masthead">
<div class="masthead__inner">
<p class="masthead__name"><a href="{prefix}index.html">{esc(p['name'])}</a></p>
<p class="masthead__role">{esc(p['role'])} &middot; <a href="{esc(p['org_url'])}">{esc(p['org'])}</a>, <a href="{esc(p['employer_url'])}">{esc(p['employer'])}</a></p>
{nav(site, page_file, prefix)}
</div>
</header>"""


def statcounter(site):
    """StatCounter, served over https and loaded async.

    The legacy snippet used http://, which an https page blocks as mixed
    content, so it may not have been recording reliably. Set
    profile.statcounter_project to "" in data/site.yaml to disable.
    """
    p = site["profile"]
    proj = str(p.get("statcounter_project") or "").strip()
    sec = str(p.get("statcounter_security") or "").strip()
    if not proj:
        return ""
    return f"""<!-- StatCounter -->
<script>
var sc_project={proj};
var sc_invisible=1;
var sc_security="{sec}";
</script>
<script src="https://secure.statcounter.com/counter/counter.js" async></script>
<noscript><div class="statcounter"><img class="statcounter"
 src="https://c.statcounter.com/{proj}/0/{sec}/1/" alt="Web Analytics"
 width="1" height="1"></div></noscript>"""


def footer(site):
    p = site["profile"]
    yr = 2026
    return f"""<footer class="foot">
<div class="foot__inner">
<span>&copy; {yr} {esc(p['name'])}</span>
<span><a href="{esc(p['scholar'])}">Google Scholar</a></span>
<span><a href="https://orcid.org/{esc(p['orcid'])}">ORCID</a></span>
<span><a href="{esc(p['github'])}">GitHub</a></span>
<span><a href="{esc(p['linkedin'])}">LinkedIn</a></span>
</div>
</footer>"""


def tagline_html(page):
    """Pages may omit the tagline; do not emit an empty <p>."""
    t = (page.get("tagline") or "").strip()
    return f"<p>{esc(t)}</p>" if t else ""


def render(site, page_file, body, extra_head="", extra_jsonld="", prefix="", page=None):
    page = page or site["pages"][page_file]
    jsonld = person_jsonld(site) if page_file == "index.html" else ""
    crumb = breadcrumb_jsonld(site, page_file, page)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
{head(site, page_file, page, prefix)}
{extra_head}
{jsonld}
{crumb}
{extra_jsonld}
</head>
<body>
<a class="skip" href="#main">Skip to content</a>
{masthead(site, page_file, prefix)}
<div class="shell">
<div class="pagehead">
<h1>{esc(page['heading'])}</h1>
{tagline_html(page)}
</div>
{body}
</div>
{footer(site)}
{statcounter(site)}
</body>
</html>
"""
